flags:
  log.parameters: false
  log.requests: true
  use:
    ssl: true
    http2: true
    jdbc: true
    ldap: true

server.ssl:
  key-store: classpath:server.p12
  key-store-password: test123
  key-password: test123
  keystoreType: PKCS12
  enabled: ${flags.use.ssl}

server:
  http2:
    enabled: ${flags.use.http2}

endpoints:
  enabled: true
  trace:
    enabled: false
  health:
    enabled: true
  info:
    enabled: true
  metrics:
    enabled: true

  cors.allowed-origins: http://localhost
  cors.allowed-methods: GET,POST

server.error.whitelabel.enabled: false


secrets:
  config:
    providers:
    - name: vault
      mount: "${SECRETS_FILE:/vault/secrets}"
      key: "${KEY_FILE:/tmp/key}"
      #if default is not set at entry level, fail, empty, identity
      error-decision: empty
      #additional entries in one file
      entries-location: "others.properties"
      ignore-resource-failure: true

datasource.jdbc:
  enabled: ${flags.use.jdbc}
  ref:
    - name: default-jdbc-client
      driver: h2
      username: sa
      password: "secret::vault::h2_password:-"
      protocol: mem
      database: "testdb"
      enabled: true
      load: "h2"

    - name: h2-1
      driver: h2
      username: sa
      password: "secret::vault::h2_password:-"
      protocol: mem
      database: "testdb2"
      enabled: true

    - name: postgresql-1
      driver: postgresql
      username: todoservice
      password: "secret::vault::postgres_password:-password"
      host: localhost
      port: 5432
      enabled: false

ldap:
  host: "192.168.99.100"
  port: 389 #389 without ssl, 636 with ssl
  baseDn: "dc=example,dc=org"
  username: "cn=admin,dc=example,dc=org"
  password: "admin"
  ssl: false
  timeout: 0
  enabled: ${flags.use.ldap}